### ISSUE TITLE
Don't map special objects

### ISSUE THREAD

**Issue by virzen** [odynvolk/map-keys-deep-lodash#1]
Hi! 

I was recently using function for mapping nested objects' keys based on yours. While doing it, I noticed that it maps special objects, like instances of `File` (i. e. `new File`) in same way it does plain ones. This doesn't seem like expected behaviour, and can be fixed in a very simple way: by replacing `isObject` with `isPlainObject`. 

I would be glad to add pr fixing this and adding few test cases if you're interested.

**Comment by odynvolk** [comment]
I agree with this. There's a pull request coming that changes quite a few things. Once it's in, feel free to do a PR for this.

**Comment by odynvolk** [comment]
I did it and published a new version.

Thanks for the sugguestion!
