### ISSUE TITLE
Make output consistent

### ISSUE THREAD

**Issue by virzen** [odynvolk/map-keys-deep-lodash#2]
Hi! It's me again!

While using your package I have also noticed that output is very inconsistent. It throws an error for `undefined`, returns some very weird stuff for strings and an empty object for other primitives. What do you think about making it consistent, i. e. returning `{}` for every incorrect `obj` argument?

**Comment by odynvolk** [comment]
Hello!

Long delay, but I've now made the output more consistent. Thank you for your feedback!
