### ISSUE TITLE
Array keys appear to be mapped

### ISSUE THREAD

**Issue by james-siteclick** [odynvolk/map-keys-deep-lodash#4]
I have tried using this library for an object that contains some arrays.
For example:
```
{
  x : ['a', 'b']
}
```
The library seems to convert this to an object:
```
{
  x : {0 : 'a', 1 : 'b}
}
```
I'm not sure if this is expected behaviour - I expected it to only map object keys.

I'm guessing this is down to the underlying lodash mapKeys function.

**Comment by odynvolk** [comment]
Hi there!

Thanks for the bug report. It should be fixed now. I published a new version: 1.0.1.

Cheers!
