### ISSUE TITLE
falsy values converting to empty object

### ISSUE THREAD

**Issue by jonathanseneris** [odynvolk/map-keys-deep-lodash#6]
**when:**
```
mapKeysDeep({
  a: 1,
  b: 0,
  c: null,
  d: undefined,
  e: NaN,
  f: false
}, (value, key) => `${key}2`)

```

**expected:**
` { 
  a2: 1,
  b2: 0,
  c2: null,
  d2: undefined,
  e2: NaN,
  f2: false 
}`

**actual:**
` { 
  a2: 1,
  b2: {},
  c2: {},
  d2: {},
  e2: {},
  f2: {} 
}`

the falsy check is converting valid values to empty objects.

**Comment by odynvolk** [comment]
Hi there!

Thanks for the feedback. I just fixed it and published a new version.
